### ISSUE TITLE
Add support for profiles in Firefox

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/history-analyser#1]
## The Issue

 - Currently, when Firefox is chosen as the browser to extract history from, the default profile is chosen without asking for user input.
 - Firefox has support for multiple profiles under the `Profiles` directory. The program currently considers the first profile which ends with `.default` which is the default profile.

## Solution

 - List all the profiles present in the `Profiles` directory and ask the user to choose which profile to consider.
 - Change `history_path` based on the chosen profile.

**Comment by punndcoder28** [comment]
Hey!. Can I work on this?

**Comment by Samyak2** [comment]
Sure. If you need any help, please ask.

**Comment by punndcoder28** [comment]
Hey! I was going through the code and I noticed that you are using numbers for profile. Instead isn't using the name of the profile better and more informative?

**Comment by punndcoder28** [comment]
Hey! I've opened a PR #2 for this issue. Can you check it and let me know if you need any changes to be done.
