### ISSUE TITLE
Create requirements file

### ISSUE THREAD

**Issue by Samyak2** [Samyak2/history-analyser#3]
- Add a `requirements.txt` file containing only the required python packages to be installed through `pip`
 - This can be done by taking the output of `pip freeze` and keeping only the required packages.
 - This will be used for Travis CI
 - Refer [this link](https://pip.readthedocs.io/en/1.1/requirements.html) for more information on the requirements file.

**Comment by dhruvhacks** [comment]
@Samyak2 May I take this one?

**Comment by Samyak2** [comment]
There is already a PR for this at #4 , but since that has a few issues you can try and send your own.

**Comment by dhruvhacks** [comment]
@Samyak2 Alright! Thanks
